import type { AppProps } from "next/app";
import Head from "next/head";
import Header from "../components/Header";

import "../styles/globals.scss";

export default function App({ Component, pageProps }: AppProps) {
    console.log(Component);
    return (
        <>
            <Head>
                <title>AL Development</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Component {...pageProps} />
        </>
    );
}
